### PR TITLE
chore: payload v3 support

### PR DESCRIPTION
**Pull request by linobino1**
This PR makes the plugin compatible with PayloadCMS v.3.

I set up a little test app using payload `v3.0.0-beta.76` [here](https://github.com/linobino1/payload-blurhash-plugin/tree/payload-v3) to see if it really works.

### CODE REVIEW

**Comment by invakid404** [comment]
Hey @linobino1, thanks for the pull request! I appreciate that you've also taken the time to test this. I will take a more in-depth look later today and will come back to you.

**Review by invakid404 — APPROVED** [review]

**Comment by linobino1** [comment]
I get a `TypeError: computeBlurhash is not a function` when I import the plugin in my project.

**Comment by invakid404** [comment]
@linobino1 I just tested and I can't reproduce. I created a new PayloadCMS v3 project, installed `payload-blurhash-plugin@3`, added it to the config, and everything seems to work. If you have reproduction steps, please open an issue.

**Comment by linobino1** [comment]
@invakid404 Ah sorry, you're right, it works at least when running `npm run dev`, but `payload generate:types` and `payload generate:schema` will fail.

**Comment by invakid404** [comment]
@linobino1 I see, it fails for me as well. I'll log an issue and investigate this.

**Pull request merged**
